# Generated by Django 5.0.3 on 2024-04-03 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='background_image',
        ),
    ]
