# Generated by Django 5.0.3 on 2024-04-07 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_alter_checkout_user'),
        ('userprofile', '0003_adresses_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='shipping',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.adresses'),
        ),
    ]
