# Generated by Django 5.0.3 on 2024-04-07 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_checkout_shipping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutline',
            old_name='checkout',
            new_name='checkout_line',
        ),
    ]
