# Generated by Django 5.0.3 on 2024-04-07 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_rename_checkout_checkoutline_checkout_line'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutline',
            old_name='checkout_line',
            new_name='checkout',
        ),
    ]
