# Generated by Django 5.0.3 on 2024-04-02 14:35

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact Number', max_length=31, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='postal_code',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='street_adress',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
