# Generated by Django 5.0.3 on 2024-04-07 01:23

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_userprofile_city_alter_userprofile_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_adress', models.CharField(blank=True, max_length=225, null=True)),
                ('city', models.CharField(blank=True, max_length=225, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=225, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact Number', max_length=31, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='street_adress',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_adress',
            field=models.ManyToManyField(to='userprofile.adresses'),
        ),
    ]
