# Generated by Django 5.0.3 on 2024-04-07 02:08

import phone_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_adresses_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adresses',
            name='city',
            field=models.CharField(default='s', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresses',
            name='phone',
            field=phone_field.models.PhoneField(default='s', help_text='Contact Number', max_length=31),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresses',
            name='postal_code',
            field=models.CharField(default='s', max_length=225),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='adresses',
            name='street_adress',
            field=models.CharField(default='s', max_length=225),
            preserve_default=False,
        ),
    ]
