# Generated by Django 5.0.3 on 2024-04-08 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_shipping_order_total'),
        ('userprofile', '0004_alter_adresses_city_alter_adresses_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='userprofile.adresses'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[(0, 'Unfullfiled'), (1, 'Fullfiled'), (2, 'Canceled'), (3, 'Refunded')], default=0),
        ),
    ]
